-- ============================================================================
-- 01_EXECUTIVE_KPIS.SQL
-- Executive C-Suite & Financial Performance Queries (Queries 1 to 7)
-- Business Rule: Realized commercial transactions are defined as orders with
-- order_status IN ('Delivered', 'Shipped'). Cancelled and returned transactions
-- are excluded to prevent revenue overstatement.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Query 1: Total Realized Revenue
-- Business Question: What is the total realized net revenue generated by the business,
-- and how much gross revenue was discounted?
-- Purpose: Top-line revenue health metric for executive reporting.
-- ----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(oi.gross_revenue), 2) AS total_gross_revenue,
    ROUND(SUM(oi.discount_amount), 2) AS total_discount_given,
    ROUND(SUM(oi.net_revenue), 2) AS total_realized_revenue,
    ROUND((SUM(oi.discount_amount) * 100.0 / SUM(oi.gross_revenue)), 2) AS effective_discount_rate_pct
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status IN ('Delivered', 'Shipped');


-- ----------------------------------------------------------------------------
-- Query 2: Total Realized Profit & Margin
-- Business Question: What is the total net profit and overall profit margin realized
-- across all fulfilled commercial sales?
-- Purpose: Bottom-line profitability evaluation and unit economics baseline.
-- ----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
    ROUND(SUM(oi.total_cost), 2) AS total_product_cost,
    ROUND(SUM(oi.profit), 2) AS total_realized_profit,
    ROUND((SUM(oi.profit) * 100.0 / SUM(oi.net_revenue)), 2) AS overall_profit_margin_pct
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status IN ('Delivered', 'Shipped');


-- ----------------------------------------------------------------------------
-- Query 3: Total Orders & Order Status Breakdown
-- Business Question: What is the total order volume and percentage distribution
-- across order fulfillment stages (Delivered, Shipped, Processing, Cancelled, Returned)?
-- Purpose: Operational logistics, fulfillment pipeline health, and cancellation monitoring.
-- ----------------------------------------------------------------------------
SELECT 
    order_status,
    COUNT(order_id) AS total_orders,
    ROUND(COUNT(order_id) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS pct_of_total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;


-- ----------------------------------------------------------------------------
-- Query 4: Average Order Value (AOV)
-- Business Question: What is the Average Order Value (AOV) and average items per basket?
-- Purpose: Pricing optimization, cross-selling benchmark, and checkout basket sizing.
-- ----------------------------------------------------------------------------
WITH order_summary AS (
    SELECT 
        o.order_id,
        SUM(oi.net_revenue) AS order_net_revenue,
        SUM(oi.quantity) AS order_total_quantity
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY o.order_id
)
SELECT 
    COUNT(order_id) AS fulfilled_order_count,
    ROUND(AVG(order_net_revenue), 2) AS average_order_value_aov,
    ROUND(AVG(order_total_quantity), 2) AS average_units_per_order
FROM order_summary;


-- ----------------------------------------------------------------------------
-- Query 5: Monthly Revenue Trend
-- Business Question: How has net sales revenue and volume trended chronologically month-by-month?
-- Purpose: Time-series revenue momentum tracking, seasonality discovery, and budget pacing.
-- ----------------------------------------------------------------------------
SELECT 
    SUBSTR(o.order_date, 1, 7) AS order_month,
    COUNT(DISTINCT o.order_id) AS monthly_orders,
    SUM(oi.quantity) AS total_units_sold,
    ROUND(SUM(oi.gross_revenue), 2) AS monthly_gross_revenue,
    ROUND(SUM(oi.discount_amount), 2) AS monthly_discounts,
    ROUND(SUM(oi.net_revenue), 2) AS monthly_net_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY SUBSTR(o.order_date, 1, 7)
ORDER BY order_month ASC;


-- ----------------------------------------------------------------------------
-- Query 6: Monthly Profit and Profit Margin Trend
-- Business Question: How do monthly bottom-line profit and profit margins fluctuate over time?
-- Purpose: Identify margin compression months due to promotional discounting or cost shifts.
-- ----------------------------------------------------------------------------
SELECT 
    SUBSTR(o.order_date, 1, 7) AS order_month,
    ROUND(SUM(oi.net_revenue), 2) AS monthly_net_revenue,
    ROUND(SUM(oi.total_cost), 2) AS monthly_cost,
    ROUND(SUM(oi.profit), 2) AS monthly_net_profit,
    ROUND((SUM(oi.profit) * 100.0 / SUM(oi.net_revenue)), 2) AS monthly_profit_margin_pct
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY SUBSTR(o.order_date, 1, 7)
ORDER BY order_month ASC;


-- ----------------------------------------------------------------------------
-- Query 7: Year-over-Year (YoY) Revenue Growth using LAG()
-- Business Question: What is the Year-over-Year (YoY) revenue percentage growth rate
-- for each calendar month compared to the exact same month in the prior year?
-- Purpose: Long-term business expansion and seasonal compounding performance analysis.
-- ----------------------------------------------------------------------------
WITH monthly_sales AS (
    SELECT 
        CAST(SUBSTR(o.order_date, 1, 4) AS INT) AS order_year,
        CAST(SUBSTR(o.order_date, 6, 2) AS INT) AS order_month_num,
        SUBSTR(o.order_date, 1, 7) AS year_month,
        ROUND(SUM(oi.net_revenue), 2) AS net_revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY order_year, order_month_num, year_month
),
yoy_growth AS (
    SELECT 
        year_month,
        order_year,
        order_month_num,
        net_revenue AS current_year_revenue,
        LAG(net_revenue, 1) OVER (
            PARTITION BY order_month_num 
            ORDER BY order_year ASC
        ) AS prior_year_revenue
    FROM monthly_sales
)
SELECT 
    year_month,
    current_year_revenue,
    prior_year_revenue,
    ROUND(current_year_revenue - prior_year_revenue, 2) AS revenue_yoy_dollar_change,
    CASE 
        WHEN prior_year_revenue IS NULL THEN NULL
        WHEN prior_year_revenue = 0 THEN NULL
        ELSE ROUND(((current_year_revenue - prior_year_revenue) * 100.0 / prior_year_revenue), 2)
    END AS yoy_growth_rate_pct
FROM yoy_growth
ORDER BY year_month ASC;