-- ============================================================================
-- E-COMMERCE SALES, CUSTOMER INTELLIGENCE & BUSINESS ANALYTICS PLATFORM
-- MASTER SQL ANALYTICAL QUERIES SUITE (QUERIES 1 TO 25)
-- Database: SQLite (data/processed/cleaned_ecommerce.db)
--
-- BUSINESS RULES & CONVENTIONS:
-- 1. Realized Business Activity: Orders with status IN ('Delivered', 'Shipped')
--    represent completed/in-flight commercial value. Cancelled ('Cancelled')
--    and Returned ('Returned') orders are excluded from net sales & profit KPIs.
-- 2. Financial Reconciliation:
--    Gross Revenue = Quantity * Unit Price
--    Discount Amount = Gross Revenue * Discount Rate
--    Net Revenue = Gross Revenue - Discount Amount
--    Total Cost = Quantity * Unit Cost
--    Profit = Net Revenue - Total Cost
--    Profit Margin % = (Profit / Net Revenue) * 100
-- ============================================================================

﻿-- ============================================================================
-- 01_EXECUTIVE_KPIS.SQL
-- Executive C-Suite & Financial Performance Queries (Queries 1 to 7)
-- Business Rule: Realized commercial transactions are defined as orders with
-- order_status IN ('Delivered', 'Shipped'). Cancelled and returned transactions
-- are excluded to prevent revenue overstatement.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Query 1: Total Realized Revenue
-- Business Question: What is the total realized net revenue generated by the business,
-- and how much gross revenue was discounted?
-- Purpose: Top-line revenue health metric for executive reporting.
-- ----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(oi.gross_revenue), 2) AS total_gross_revenue,
    ROUND(SUM(oi.discount_amount), 2) AS total_discount_given,
    ROUND(SUM(oi.net_revenue), 2) AS total_realized_revenue,
    ROUND((SUM(oi.discount_amount) * 100.0 / SUM(oi.gross_revenue)), 2) AS effective_discount_rate_pct
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status IN ('Delivered', 'Shipped');


-- ----------------------------------------------------------------------------
-- Query 2: Total Realized Profit & Margin
-- Business Question: What is the total net profit and overall profit margin realized
-- across all fulfilled commercial sales?
-- Purpose: Bottom-line profitability evaluation and unit economics baseline.
-- ----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
    ROUND(SUM(oi.total_cost), 2) AS total_product_cost,
    ROUND(SUM(oi.profit), 2) AS total_realized_profit,
    ROUND((SUM(oi.profit) * 100.0 / SUM(oi.net_revenue)), 2) AS overall_profit_margin_pct
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status IN ('Delivered', 'Shipped');


-- ----------------------------------------------------------------------------
-- Query 3: Total Orders & Order Status Breakdown
-- Business Question: What is the total order volume and percentage distribution
-- across order fulfillment stages (Delivered, Shipped, Processing, Cancelled, Returned)?
-- Purpose: Operational logistics, fulfillment pipeline health, and cancellation monitoring.
-- ----------------------------------------------------------------------------
SELECT 
    order_status,
    COUNT(order_id) AS total_orders,
    ROUND(COUNT(order_id) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS pct_of_total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;


-- ----------------------------------------------------------------------------
-- Query 4: Average Order Value (AOV)
-- Business Question: What is the Average Order Value (AOV) and average items per basket?
-- Purpose: Pricing optimization, cross-selling benchmark, and checkout basket sizing.
-- ----------------------------------------------------------------------------
WITH order_summary AS (
    SELECT 
        o.order_id,
        SUM(oi.net_revenue) AS order_net_revenue,
        SUM(oi.quantity) AS order_total_quantity
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY o.order_id
)
SELECT 
    COUNT(order_id) AS fulfilled_order_count,
    ROUND(AVG(order_net_revenue), 2) AS average_order_value_aov,
    ROUND(AVG(order_total_quantity), 2) AS average_units_per_order
FROM order_summary;


-- ----------------------------------------------------------------------------
-- Query 5: Monthly Revenue Trend
-- Business Question: How has net sales revenue and volume trended chronologically month-by-month?
-- Purpose: Time-series revenue momentum tracking, seasonality discovery, and budget pacing.
-- ----------------------------------------------------------------------------
SELECT 
    SUBSTR(o.order_date, 1, 7) AS order_month,
    COUNT(DISTINCT o.order_id) AS monthly_orders,
    SUM(oi.quantity) AS total_units_sold,
    ROUND(SUM(oi.gross_revenue), 2) AS monthly_gross_revenue,
    ROUND(SUM(oi.discount_amount), 2) AS monthly_discounts,
    ROUND(SUM(oi.net_revenue), 2) AS monthly_net_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY SUBSTR(o.order_date, 1, 7)
ORDER BY order_month ASC;


-- ----------------------------------------------------------------------------
-- Query 6: Monthly Profit and Profit Margin Trend
-- Business Question: How do monthly bottom-line profit and profit margins fluctuate over time?
-- Purpose: Identify margin compression months due to promotional discounting or cost shifts.
-- ----------------------------------------------------------------------------
SELECT 
    SUBSTR(o.order_date, 1, 7) AS order_month,
    ROUND(SUM(oi.net_revenue), 2) AS monthly_net_revenue,
    ROUND(SUM(oi.total_cost), 2) AS monthly_cost,
    ROUND(SUM(oi.profit), 2) AS monthly_net_profit,
    ROUND((SUM(oi.profit) * 100.0 / SUM(oi.net_revenue)), 2) AS monthly_profit_margin_pct
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY SUBSTR(o.order_date, 1, 7)
ORDER BY order_month ASC;


-- ----------------------------------------------------------------------------
-- Query 7: Year-over-Year (YoY) Revenue Growth using LAG()
-- Business Question: What is the Year-over-Year (YoY) revenue percentage growth rate
-- for each calendar month compared to the exact same month in the prior year?
-- Purpose: Long-term business expansion and seasonal compounding performance analysis.
-- ----------------------------------------------------------------------------
WITH monthly_sales AS (
    SELECT 
        CAST(SUBSTR(o.order_date, 1, 4) AS INT) AS order_year,
        CAST(SUBSTR(o.order_date, 6, 2) AS INT) AS order_month_num,
        SUBSTR(o.order_date, 1, 7) AS year_month,
        ROUND(SUM(oi.net_revenue), 2) AS net_revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY order_year, order_month_num, year_month
),
yoy_growth AS (
    SELECT 
        year_month,
        order_year,
        order_month_num,
        net_revenue AS current_year_revenue,
        LAG(net_revenue, 1) OVER (
            PARTITION BY order_month_num 
            ORDER BY order_year ASC
        ) AS prior_year_revenue
    FROM monthly_sales
)
SELECT 
    year_month,
    current_year_revenue,
    prior_year_revenue,
    ROUND(current_year_revenue - prior_year_revenue, 2) AS revenue_yoy_dollar_change,
    CASE 
        WHEN prior_year_revenue IS NULL THEN NULL
        WHEN prior_year_revenue = 0 THEN NULL
        ELSE ROUND(((current_year_revenue - prior_year_revenue) * 100.0 / prior_year_revenue), 2)
    END AS yoy_growth_rate_pct
FROM yoy_growth
ORDER BY year_month ASC;

﻿-- ============================================================================
-- 02_SALES_AND_PRODUCT_ANALYTICS.SQL
-- Product Performance, Category Dynamics, Geography & Pricing Strategy
-- Queries: 8, 9, 10, 11, 12, 13, 18, 19, 20
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Query 8: Top 10 Products by Revenue (Using DENSE_RANK())
-- Business Question: Which top 10 catalog items contribute the highest net sales volume?
-- Purpose: Merchandising priority, inventory allocation, and flagship product monitoring.
-- ----------------------------------------------------------------------------
WITH product_sales AS (
    SELECT 
        p.product_id,
        p.product_name,
        p.category,
        p.sub_category,
        SUM(oi.quantity) AS total_units_sold,
        ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
        DENSE_RANK() OVER (ORDER BY SUM(oi.net_revenue) DESC) AS revenue_rank
    FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY p.product_id, p.product_name, p.category, p.sub_category
)
SELECT 
    revenue_rank,
    product_id,
    product_name,
    category,
    sub_category,
    total_units_sold,
    total_net_revenue
FROM product_sales
WHERE revenue_rank <= 10
ORDER BY revenue_rank ASC;


-- ----------------------------------------------------------------------------
-- Query 9: Top 10 Products by Profit and Margin
-- Business Question: Which top 10 products generate the highest cumulative gross profit dollar value?
-- Purpose: Profit driver analysis and marketing budget prioritization.
-- ----------------------------------------------------------------------------
WITH product_profit AS (
    SELECT 
        p.product_id,
        p.product_name,
        p.category,
        ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
        ROUND(SUM(oi.profit), 2) AS total_profit,
        ROUND((SUM(oi.profit) * 100.0 / SUM(oi.net_revenue)), 2) AS profit_margin_pct,
        DENSE_RANK() OVER (ORDER BY SUM(oi.profit) DESC) AS profit_rank
    FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY p.product_id, p.product_name, p.category
)
SELECT 
    profit_rank,
    product_id,
    product_name,
    category,
    total_net_revenue,
    total_profit,
    profit_margin_pct
FROM product_profit
WHERE profit_rank <= 10
ORDER BY profit_rank ASC;


-- ----------------------------------------------------------------------------
-- Query 10: Best-Performing Product Categories
-- Business Question: What are the revenue, profit, and margin contributions of each product category?
-- Purpose: Portfolio management and category management strategy.
-- ----------------------------------------------------------------------------
SELECT 
    p.category,
    COUNT(DISTINCT oi.order_id) AS order_count,
    SUM(oi.quantity) AS total_units_sold,
    ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
    ROUND(SUM(oi.profit), 2) AS total_profit,
    ROUND((SUM(oi.profit) * 100.0 / SUM(oi.net_revenue)), 2) AS profit_margin_pct
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY p.category
ORDER BY total_net_revenue DESC;


-- ----------------------------------------------------------------------------
-- Query 11: Worst-Performing Categories / Loss Centers
-- Business Question: Which categories or sub-categories generate the lowest profit margins?
-- Purpose: Identify product lines requiring supplier renegotiation or rationalization.
-- ----------------------------------------------------------------------------
SELECT 
    p.category,
    p.sub_category,
    SUM(oi.quantity) AS units_sold,
    ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
    ROUND(SUM(oi.profit), 2) AS total_profit,
    ROUND((SUM(oi.profit) * 100.0 / SUM(oi.net_revenue)), 2) AS profit_margin_pct,
    ROUND(AVG(oi.discount_rate) * 100.0, 2) AS avg_discount_pct
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY p.category, p.sub_category
ORDER BY total_profit ASC
LIMIT 10;


-- ----------------------------------------------------------------------------
-- Query 12: Revenue by State / Region
-- Business Question: How is realized customer revenue distributed geographically across US states?
-- Purpose: Regional marketing spend targeting and supply chain warehouse optimization.
-- ----------------------------------------------------------------------------
SELECT 
    c.state,
    COUNT(DISTINCT o.order_id) AS total_orders,
    COUNT(DISTINCT c.customer_id) AS unique_customers,
    ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
    ROUND(SUM(oi.profit), 2) AS total_profit,
    ROUND(SUM(oi.net_revenue) / COUNT(DISTINCT o.order_id), 2) AS state_avg_order_value
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY c.state
ORDER BY total_net_revenue DESC;


-- ----------------------------------------------------------------------------
-- Query 13: Revenue by Top 20 Cities
-- Business Question: Which top 20 metropolitan cities drive the largest share of commercial revenue?
-- Purpose: Hyper-local ad targeting and metropolitan distribution hub selection.
-- ----------------------------------------------------------------------------
SELECT 
    c.city,
    c.state,
    COUNT(DISTINCT o.order_id) AS order_count,
    COUNT(DISTINCT c.customer_id) AS customer_count,
    ROUND(SUM(oi.net_revenue), 2) AS total_net_revenue,
    ROUND(SUM(oi.profit), 2) AS total_profit
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY c.city, c.state
ORDER BY total_net_revenue DESC
LIMIT 20;


-- ----------------------------------------------------------------------------
-- Query 18: Products with Declining Sales using Window Functions
-- Business Question: Which products experienced consecutive quarterly revenue decline?
-- Purpose: Early warning churn signal for catalog items losing consumer demand.
-- ----------------------------------------------------------------------------
WITH product_quarterly_sales AS (
    SELECT 
        p.product_id,
        p.product_name,
        p.category,
        SUBSTR(o.order_date, 1, 4) || '-Q' || ((CAST(SUBSTR(o.order_date, 6, 2) AS INT) - 1) / 3 + 1) AS sales_quarter,
        SUM(oi.net_revenue) AS quarter_revenue
    FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY p.product_id, p.product_name, p.category, sales_quarter
),
quarterly_comparison AS (
    SELECT 
        product_id,
        product_name,
        category,
        sales_quarter,
        quarter_revenue,
        LAG(quarter_revenue, 1) OVER (
            PARTITION BY product_id 
            ORDER BY sales_quarter ASC
        ) AS prev_quarter_revenue
    FROM product_quarterly_sales
)
SELECT 
    product_id,
    product_name,
    category,
    sales_quarter,
    ROUND(quarter_revenue, 2) AS current_quarter_rev,
    ROUND(prev_quarter_revenue, 2) AS prior_quarter_rev,
    ROUND(quarter_revenue - prev_quarter_revenue, 2) AS revenue_decline_amount,
    ROUND(((quarter_revenue - prev_quarter_revenue) * 100.0 / prev_quarter_revenue), 2) AS decline_pct
FROM quarterly_comparison
WHERE prev_quarter_revenue IS NOT NULL 
  AND quarter_revenue < prev_quarter_revenue
ORDER BY revenue_decline_amount ASC
LIMIT 15;


-- ----------------------------------------------------------------------------
-- Query 19: Discount vs Profit Analysis
-- Business Question: How do promotional discount tiers affect sales volume and margin erosion?
-- Purpose: Establish discount ceilings to protect profit margins.
-- ----------------------------------------------------------------------------
SELECT 
    CASE 
        WHEN discount_rate = 0.0 THEN '0% (Full Price)'
        WHEN discount_rate > 0.0 AND discount_rate <= 0.10 THEN '1% - 10% (Low Discount)'
        WHEN discount_rate > 0.10 AND discount_rate <= 0.20 THEN '11% - 20% (Medium Discount)'
        WHEN discount_rate > 0.20 THEN '21%+ (Heavy Promo)'
        ELSE 'Other'
    END AS discount_tier,
    COUNT(order_item_id) AS line_item_count,
    SUM(quantity) AS total_units_sold,
    ROUND(SUM(gross_revenue), 2) AS total_gross_revenue,
    ROUND(SUM(discount_amount), 2) AS total_discount_amount,
    ROUND(SUM(net_revenue), 2) AS total_net_revenue,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND((SUM(profit) * 100.0 / SUM(net_revenue)), 2) AS effective_profit_margin_pct
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY discount_tier
ORDER BY total_net_revenue DESC;


-- ----------------------------------------------------------------------------
-- Query 20: Revenue Contribution by Category and Cumulative Pareto %
-- Business Question: What is the individual and cumulative Pareto revenue share of each product category?
-- Purpose: Apply the 80/20 rule to determine core revenue-generating business pillars.
-- ----------------------------------------------------------------------------
WITH category_totals AS (
    SELECT 
        p.category,
        ROUND(SUM(oi.net_revenue), 2) AS category_revenue,
        ROUND(SUM(oi.profit), 2) AS category_profit
    FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY p.category
),
category_pareto AS (
    SELECT 
        category,
        category_revenue,
        category_profit,
        ROUND(category_revenue * 100.0 / SUM(category_revenue) OVER (), 2) AS pct_of_total_revenue,
        ROUND(SUM(category_revenue) OVER (ORDER BY category_revenue DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) * 100.0 / SUM(category_revenue) OVER (), 2) AS cumulative_pareto_revenue_pct
    FROM category_totals
)
SELECT 
    category,
    category_revenue,
    category_profit,
    pct_of_total_revenue,
    cumulative_pareto_revenue_pct
FROM category_pareto
ORDER BY category_revenue DESC;

﻿-- ============================================================================
-- 03_CUSTOMER_INTELLIGENCE_AND_RETENTION.SQL
-- Customer Behavior, Retention, RFM Segmentation & Churn Risk
-- Queries: 14, 15, 16, 17, 21, 22, 23, 24, 25
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Query 14: New vs Returning Customers by Month
-- Business Question: What proportion of monthly sales comes from new vs returning shoppers?
-- Purpose: Measure reliance on customer acquisition vs organic retention.
-- ----------------------------------------------------------------------------
WITH customer_first_order AS (
    SELECT 
        customer_id,
        MIN(order_date) AS first_order_date,
        SUBSTR(MIN(order_date), 1, 7) AS first_order_month
    FROM orders
    WHERE order_status IN ('Delivered', 'Shipped')
    GROUP BY customer_id
),
order_classification AS (
    SELECT 
        o.order_id,
        o.customer_id,
        SUBSTR(o.order_date, 1, 7) AS order_month,
        SUM(oi.net_revenue) AS order_revenue,
        CASE 
            WHEN SUBSTR(o.order_date, 1, 7) = cfo.first_order_month THEN 'New Customer'
            ELSE 'Returning Customer'
        END AS customer_type
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN customer_first_order cfo ON o.customer_id = cfo.customer_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY o.order_id, o.customer_id, o.order_date, cfo.first_order_month
)
SELECT 
    order_month,
    SUM(CASE WHEN customer_type = 'New Customer' THEN 1 ELSE 0 END) AS new_customer_orders,
    SUM(CASE WHEN customer_type = 'Returning Customer' THEN 1 ELSE 0 END) AS returning_customer_orders,
    ROUND(SUM(CASE WHEN customer_type = 'New Customer' THEN order_revenue ELSE 0 END), 2) AS new_customer_revenue,
    ROUND(SUM(CASE WHEN customer_type = 'Returning Customer' THEN order_revenue ELSE 0 END), 2) AS returning_customer_revenue,
    ROUND(SUM(CASE WHEN customer_type = 'Returning Customer' THEN order_revenue ELSE 0 END) * 100.0 / SUM(order_revenue), 2) AS returning_revenue_share_pct
FROM order_classification
GROUP BY order_month
ORDER BY order_month ASC;


-- ----------------------------------------------------------------------------
-- Query 15: Repeat Purchase Rate (RPR)
-- Business Question: What percentage of unique acquired customers place multiple orders?
-- Purpose: Core customer stickiness and product-market fit indicator.
-- ----------------------------------------------------------------------------
WITH customer_order_counts AS (
    SELECT 
        customer_id,
        COUNT(order_id) AS total_orders
    FROM orders
    WHERE order_status IN ('Delivered', 'Shipped')
    GROUP BY customer_id
)
SELECT 
    COUNT(customer_id) AS total_active_customers,
    SUM(CASE WHEN total_orders = 1 THEN 1 ELSE 0 END) AS single_order_customers,
    SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END) AS repeat_customers,
    ROUND(SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(customer_id), 2) AS repeat_purchase_rate_pct
FROM customer_order_counts;


-- ----------------------------------------------------------------------------
-- Query 16: Average Customer Lifetime Value (CLV)
-- Business Question: What is the average realized Lifetime Value and Profit per customer segment?
-- Purpose: Establish Customer Acquisition Cost (CAC) thresholds and segment targeting.
-- ----------------------------------------------------------------------------
WITH customer_financials AS (
    SELECT 
        c.customer_id,
        c.customer_segment,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(oi.net_revenue) AS total_lifetime_revenue,
        SUM(oi.profit) AS total_lifetime_profit
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY c.customer_id, c.customer_segment
)
SELECT 
    customer_segment,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(total_orders), 2) AS avg_orders_per_customer,
    ROUND(AVG(total_lifetime_revenue), 2) AS avg_customer_lifetime_value_clv,
    ROUND(AVG(total_lifetime_profit), 2) AS avg_customer_lifetime_profit
FROM customer_financials
GROUP BY customer_segment
ORDER BY avg_customer_lifetime_value_clv DESC;


-- ----------------------------------------------------------------------------
-- Query 17: Top Spending Customers (VIPs)
-- Business Question: Who are the top 20 highest-spending VIP accounts on the platform?
-- Purpose: Concierge account management, loyalty rewards, and VIP retention.
-- ----------------------------------------------------------------------------
WITH customer_spend AS (
    SELECT 
        c.customer_id,
        c.customer_name,
        c.city,
        c.state,
        c.customer_segment,
        COUNT(DISTINCT o.order_id) AS completed_orders,
        SUM(oi.quantity) AS total_items_purchased,
        ROUND(SUM(oi.net_revenue), 2) AS total_net_spend,
        ROUND(SUM(oi.profit), 2) AS total_profit_generated,
        DENSE_RANK() OVER (ORDER BY SUM(oi.net_revenue) DESC) AS spend_rank
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY c.customer_id, c.customer_name, c.city, c.state, c.customer_segment
)
SELECT 
    spend_rank,
    customer_id,
    customer_name,
    city,
    state,
    customer_segment,
    completed_orders,
    total_items_purchased,
    total_net_spend,
    total_profit_generated
FROM customer_spend
WHERE spend_rank <= 20
ORDER BY spend_rank ASC;


-- ----------------------------------------------------------------------------
-- Query 21: Monthly Active Customers (MAC / MAU)
-- Business Question: How many distinct active customers transacted each month?
-- Purpose: Monitor platform monthly active user retention and transaction velocity.
-- ----------------------------------------------------------------------------
SELECT 
    SUBSTR(o.order_date, 1, 7) AS active_month,
    COUNT(DISTINCT o.customer_id) AS monthly_active_customers,
    COUNT(DISTINCT o.order_id) AS total_monthly_orders,
    ROUND(COUNT(DISTINCT o.order_id) * 1.0 / COUNT(DISTINCT o.customer_id), 2) AS orders_per_active_customer,
    ROUND(SUM(oi.net_revenue) / COUNT(DISTINCT o.customer_id), 2) AS revenue_per_active_customer
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status IN ('Delivered', 'Shipped')
GROUP BY SUBSTR(o.order_date, 1, 7)
ORDER BY active_month ASC;


-- ----------------------------------------------------------------------------
-- Query 22: Customer Cohort Retention Matrix
-- Business Question: What percentage of newly acquired users return in subsequent months (M+0 to M+6)?
-- Purpose: Measure long-term platform stickiness and cohort decay curves.
-- ----------------------------------------------------------------------------
WITH customer_cohort AS (
    SELECT 
        customer_id,
        SUBSTR(MIN(order_date), 1, 7) AS cohort_month
    FROM orders
    WHERE order_status IN ('Delivered', 'Shipped')
    GROUP BY customer_id
),
user_activities AS (
    SELECT 
        o.customer_id,
        cc.cohort_month,
        (CAST(SUBSTR(o.order_date, 1, 4) AS INT) - CAST(SUBSTR(cc.cohort_month, 1, 4) AS INT)) * 12 +
        (CAST(SUBSTR(o.order_date, 6, 2) AS INT) - CAST(SUBSTR(cc.cohort_month, 6, 2) AS INT)) AS month_number
    FROM orders o
    JOIN customer_cohort cc ON o.customer_id = cc.customer_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY o.customer_id, cc.cohort_month, month_number
),
cohort_size AS (
    SELECT 
        cohort_month,
        COUNT(DISTINCT customer_id) AS total_cohort_size
    FROM customer_cohort
    GROUP BY cohort_month
)
SELECT 
    ua.cohort_month,
    cs.total_cohort_size,
    ua.month_number,
    COUNT(DISTINCT ua.customer_id) AS active_users,
    ROUND(COUNT(DISTINCT ua.customer_id) * 100.0 / cs.total_cohort_size, 2) AS retention_rate_pct
FROM user_activities ua
JOIN cohort_size cs ON ua.cohort_month = cs.cohort_month
WHERE ua.month_number <= 6
GROUP BY ua.cohort_month, cs.total_cohort_size, ua.month_number
ORDER BY ua.cohort_month ASC, ua.month_number ASC;


-- ----------------------------------------------------------------------------
-- Query 23: RFM Customer Segmentation (NTILE Scoring)
-- Business Question: How are customers grouped into actionable behavioral personas
-- using Recency, Frequency, and Monetary scores?
-- Purpose: Precision email marketing, loyalty incentives, and retention campaigns.
-- ----------------------------------------------------------------------------
WITH rfm_raw AS (
    SELECT 
        c.customer_id,
        c.customer_name,
        c.email,
        c.city,
        c.state,
        MAX(o.order_date) AS last_order_date,
        CAST(JULIANDAY('2026-06-30') - JULIANDAY(MAX(o.order_date)) AS INT) AS recency_days,
        COUNT(DISTINCT o.order_id) AS frequency,
        ROUND(SUM(oi.net_revenue), 2) AS monetary_value
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY c.customer_id, c.customer_name, c.email, c.city, c.state
),
rfm_scores AS (
    SELECT 
        customer_id,
        customer_name,
        email,
        city,
        state,
        recency_days,
        frequency,
        monetary_value,
        NTILE(5) OVER (ORDER BY recency_days DESC) AS r_score,
        NTILE(5) OVER (ORDER BY frequency ASC) AS f_score,
        NTILE(5) OVER (ORDER BY monetary_value ASC) AS m_score
    FROM rfm_raw
),
rfm_segmented AS (
    SELECT 
        customer_id,
        customer_name,
        email,
        city,
        state,
        recency_days,
        frequency,
        monetary_value,
        r_score,
        f_score,
        m_score,
        (r_score || f_score || m_score) AS rfm_combined,
        CASE 
            WHEN r_score >= 4 AND f_score >= 4 AND m_score >= 4 THEN 'Champions'
            WHEN r_score >= 3 AND f_score >= 3 AND m_score >= 3 THEN 'Loyal Customers'
            WHEN r_score >= 4 AND f_score <= 2 THEN 'Recent Customers'
            WHEN r_score >= 3 AND f_score <= 2 AND m_score >= 3 THEN 'Promising'
            WHEN r_score <= 2 AND f_score >= 3 AND m_score >= 3 THEN 'At Risk Customers'
            WHEN r_score = 1 AND f_score >= 4 THEN 'Can’t Lose Them'
            WHEN r_score <= 2 AND f_score <= 2 THEN 'Hibernating / Lost'
            ELSE 'Need Attention'
        END AS rfm_segment
    FROM rfm_scores
)
SELECT 
    rfm_segment,
    COUNT(customer_id) AS customer_count,
    ROUND(AVG(recency_days), 1) AS avg_recency_days,
    ROUND(AVG(frequency), 2) AS avg_orders,
    ROUND(AVG(monetary_value), 2) AS avg_monetary_spend,
    ROUND(SUM(monetary_value), 2) AS total_segment_revenue,
    ROUND(SUM(monetary_value) * 100.0 / (SELECT SUM(net_revenue) FROM order_items oi JOIN orders o ON oi.order_id=o.order_id WHERE o.order_status IN ('Delivered','Shipped')), 2) AS pct_revenue_contribution
FROM rfm_segmented
GROUP BY rfm_segment
ORDER BY total_segment_revenue DESC;


-- ----------------------------------------------------------------------------
-- Query 24: Top 10% Decile Customer Contribution to Revenue (NTILE(10))
-- Business Question: What percentage of total revenue is concentrated in the top 10% of spenders?
-- Purpose: Validate Pareto 80/20 revenue concentration risks.
-- ----------------------------------------------------------------------------
WITH customer_spend AS (
    SELECT 
        c.customer_id,
        SUM(oi.net_revenue) AS total_customer_spend
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY c.customer_id
),
deciles AS (
    SELECT 
        customer_id,
        total_customer_spend,
        NTILE(10) OVER (ORDER BY total_customer_spend ASC) AS spend_decile
    FROM customer_spend
)
SELECT 
    spend_decile,
    COUNT(customer_id) AS customer_count,
    ROUND(MIN(total_customer_spend), 2) AS min_spend_in_decile,
    ROUND(MAX(total_customer_spend), 2) AS max_spend_in_decile,
    ROUND(SUM(total_customer_spend), 2) AS total_decile_revenue,
    ROUND(SUM(total_customer_spend) * 100.0 / (SELECT SUM(total_customer_spend) FROM customer_spend), 2) AS decile_revenue_share_pct
FROM deciles
GROUP BY spend_decile
ORDER BY spend_decile DESC;


-- ----------------------------------------------------------------------------
-- Query 25: Churn Risk Detection (Inactive > 90 / 180 Days with Repeat Order History)
-- Business Question: Which previously active repeat customers have stopped buying and are at risk of churning?
-- Purpose: Win-back marketing and reactivation discount trigger lists.
-- ----------------------------------------------------------------------------
WITH customer_inactivity AS (
    SELECT 
        c.customer_id,
        c.customer_name,
        c.email,
        c.city,
        c.state,
        MAX(o.order_date) AS last_order_date,
        CAST(JULIANDAY('2026-06-30') - JULIANDAY(MAX(o.order_date)) AS INT) AS days_inactive,
        COUNT(DISTINCT o.order_id) AS historic_orders,
        ROUND(SUM(oi.net_revenue), 2) AS historic_lifetime_spend
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status IN ('Delivered', 'Shipped')
    GROUP BY c.customer_id, c.customer_name, c.email, c.city, c.state
)
SELECT 
    customer_id,
    customer_name,
    email,
    city,
    state,
    historic_orders,
    historic_lifetime_spend,
    last_order_date,
    days_inactive,
    CASE 
        WHEN days_inactive >= 270 THEN 'Severe Churn Risk (9+ Months Inactive)'
        WHEN days_inactive >= 180 THEN 'High Churn Risk (6-9 Months Inactive)'
        WHEN days_inactive >= 90 THEN 'Moderate Churn Risk (3-6 Months Inactive)'
        ELSE 'Active'
    END AS churn_risk_tier
FROM customer_inactivity
WHERE days_inactive >= 90 AND historic_orders >= 2
ORDER BY historic_lifetime_spend DESC
LIMIT 25;